/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package musicplayer;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author acer
 */
public class musicGUI extends javax.swing.JDialog {
    
    static final int n=200;
    MusicPlayer MC=new MusicPlayer();
    public static int count;
    public static int pauseval;
    static public String []songlist = new String[n];
    static public String []fsonglist= new String[n];
    int i=0; ////for index of songlist
    int fav=0;
    int lastplay=-1,lastindex=-1,flastindex=-1;
    int temp=0;
    
   /* static
    {
        MPdao dao = new MPdao();
        int j=1;
        
           
           try {
                while(!(dao.retrieve(i)==null)&&j<=dao.count())  /////////////////////////////////////////////////
                {
                    System.out.println(i);
           
                    try {
                        songlist[i]=dao.retrieve(i);
                    } catch (Exception ex) {
                        ex.getMessage();
                    }
                    
                    
                    
                    File f = null;
                    try {
                        f = new File(songlist[i]);
                    } catch (Exception ex) {
                        ex.getMessage();
                    }
                    
                    
                    
                    sl.addItem(f.getName());
                    
                    
                   j++;
                    i++;
                    
                    
                }  } catch (Exception ex) {
                ex.getMessage();
            }
           
    }
    
    */
    
    

    /**
     * Creates new form musicGUI
     */
    public musicGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        sl = new javax.swing.JComboBox<>();
        jProgressBar1 = new javax.swing.JProgressBar();
        Play = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Stop = new javax.swing.JButton();
        prev = new javax.swing.JButton();
        Pause = new javax.swing.JButton();
        next = new javax.swing.JButton();
        SelectFile = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Loop = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        sl2 = new javax.swing.JComboBox<>();
        Display = new javax.swing.JLabel();
        loopcounter = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        sl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slActionPerformed(evt);
            }
        });

        Play.setIcon(new javax.swing.ImageIcon("C:\\Users\\Avatar-14\\Desktop\\Music Player Icons\\play4.jpg")); // NOI18N
        Play.setText("Play");
        Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Avatar-14\\Desktop\\Music Player Icons\\Database1.jpg")); // NOI18N
        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Stop.setIcon(new javax.swing.ImageIcon("C:\\Users\\Avatar-14\\Desktop\\Music Player Icons\\stop2.png")); // NOI18N
        Stop.setText("Stop");
        Stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopActionPerformed(evt);
            }
        });

        prev.setIcon(new javax.swing.ImageIcon("C:\\Users\\Avatar-14\\Desktop\\Music Player Icons\\prev1.jpg")); // NOI18N
        prev.setText("prev");
        prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevActionPerformed(evt);
            }
        });

        Pause.setIcon(new javax.swing.ImageIcon("C:\\Users\\Avatar-14\\Desktop\\Music Player Icons\\pause1.jpg")); // NOI18N
        Pause.setText("Pause");
        Pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PauseActionPerformed(evt);
            }
        });

        next.setIcon(new javax.swing.ImageIcon("C:\\Users\\Avatar-14\\Desktop\\Music Player Icons\\next1.jpg")); // NOI18N
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        SelectFile.setIcon(new javax.swing.ImageIcon("C:\\Users\\Avatar-14\\Desktop\\Music Player Icons\\browse1.jpg")); // NOI18N
        SelectFile.setText("browse");
        SelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectFileActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Avatar-14\\Desktop\\Music Player Icons\\addtolib1.jpg")); // NOI18N
        jButton1.setText("addtolib");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Loop.setIcon(new javax.swing.ImageIcon("C:\\Users\\Avatar-14\\Desktop\\Music Player Icons\\loop1.jpg")); // NOI18N
        Loop.setText("Loop");
        Loop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoopActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Avatar-14\\Desktop\\Music Player Icons\\favorite30.png")); // NOI18N
        jButton3.setText("fav");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        loopcounter.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(sl2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sl, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Loop, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loopcounter, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Stop, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(prev, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(160, 160, 160))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Play, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Pause, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)))
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(SelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(Play, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Stop, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(prev, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Loop, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(loopcounter, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(Pause, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap()))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(SelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PauseActionPerformed
        MC.Pause();
        pauseval = 0;// TODO add your handling code here:
    }//GEN-LAST:event_PauseActionPerformed

    private void PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayActionPerformed
        if(pauseval==0){
        MC.Resume();
        pauseval = 1;}
        
                 if(sl2.getSelectedIndex()!=flastindex){
             MC.Stop();
             
           File myFile = null;
            try {
                myFile = new File(fsonglist[(sl2.getSelectedIndex())]);
            } catch (Exception ex) {
                ex.getMessage();
            }
           
            try {
                System.out.println(sl2.getSelectedIndex());
            } catch (Exception ex) {
                Logger.getLogger(musicGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
              
           String name = myFile.getName();
           Display.setText(name);
            try {
                
                MC.Play(fsonglist[sl2.getSelectedIndex()]);                  ///////changed//////////////
            } catch (Exception ex) {
                ex.getMessage();
            }
            
            
            flastindex=sl2.getSelectedIndex();
        }
        
        if(sl.getSelectedIndex()!=lastindex){
             MC.Stop();
             MPdao dao = new MPdao();
           File myFile = null;
            try {
                myFile = new File(dao.retrieve(sl.getSelectedIndex()));
            } catch (Exception ex) {
                ex.getMessage();
            }
           
            try {
                System.out.println(sl.getSelectedIndex());
            } catch (Exception ex) {
                Logger.getLogger(musicGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
              
           String name = myFile.getName();
           Display.setText(name);
            try {
                
                MC.Play(songlist[sl.getSelectedIndex()]);                  ///////changed//////////////
            } catch (Exception ex) {
                ex.getMessage();
            }
            
            lastplay=sl.getSelectedIndex();
            lastindex=sl.getSelectedIndex();
        }
        

        
     /*  new Thread(){
            int x=1;
            for( ;x; )
            {
                jProgressBar1.setValue((MC.songTotalLength-MC.pauseLocation)/MC.songTotalLength*100);
            }
        
            
    }.start();*/ 
    }//GEN-LAST:event_PlayActionPerformed

    private void StopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopActionPerformed
        MC.Stop();
        pauseval=0;
        // TODO add your handling code here:
    }//GEN-LAST:event_StopActionPerformed

    private void SelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectFileActionPerformed
       
        FileFilter filter = new FileNameExtensionFilter("MP3 files","mp3","mpeg3");
       JFileChooser chooser = new JFileChooser("D:\\MultiMedia\\Music");
       chooser.addChoosableFileFilter(filter);
       int returnVal = chooser.showOpenDialog(null);
       if(returnVal == JFileChooser.APPROVE_OPTION){
           MC.Stop();
           File myFile = chooser.getSelectedFile();
           String song = myFile + "";
           String name = chooser.getSelectedFile().getName();
           Display.setText(name);
           
           MC.Play(song);
           pauseval=1;
           
  }
    }//GEN-LAST:event_SelectFileActionPerformed

    private void LoopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoopActionPerformed
        switch(count)
        {
            case 0:
                count = 1;
                loopcounter.setText("LOOP ON");
                break;
            case 1:
                count = 0;
                  loopcounter.setText("LOOP OFF");
                break;
        }
    }//GEN-LAST:event_LoopActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        if(i<n){
        JFileChooser chooser = new JFileChooser("D:\\MultiMedia\\Music");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
       int returnVal = chooser.showOpenDialog(null);
       if(returnVal == JFileChooser.APPROVE_OPTION){
           //
       }
       String dirpath=chooser.getSelectedFile().getAbsolutePath();
       
       File dir =new File(dirpath);
       for(File f : dir.listFiles()){
           if(f.getName().contains(".mp3")){
               MPdao dao = new MPdao();                          //////////////////////////
               try {
                   dao.addsong(i,f.getAbsolutePath());
                   
               } catch (Exception ex) {
                   ex.getMessage();
               }
               songlist[i++]=f.getAbsolutePath();
               sl.addItem(f.getName());
               
           }
       }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void slActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slActionPerformed
                
    }//GEN-LAST:event_slActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        
        MC.Stop();
        
        if(lastplay<i-1){
         
        File myFile = new File(songlist[lastplay+1]);
    
           String name = myFile.getName();
           Display.setText(name);
            MC.Play(songlist[lastplay+1]);
            
            lastplay++;
        }
        
        
         else
        {
            File myFile = new File(songlist[0]);
    
           String name = myFile.getName();
           Display.setText(name);
            MC.Play(songlist[0]);
            
            lastplay=0;
        }
            
    }//GEN-LAST:event_nextActionPerformed

    private void prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevActionPerformed
        
        
        if(lastplay!=0){
         MC.Stop();
        File myFile = new File(songlist[lastplay-1]);
    
           String name = myFile.getName();
           Display.setText(name);
            MC.Play(songlist[lastplay-1]);
            
            lastplay--;
        }
        
        
         else
        {              
            
            
            Display.setText("Already the first song in the list");  
            
           
        }                                                                                ////////////////////////////////////////
    }//GEN-LAST:event_prevActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         MPdao dao = new MPdao();
        int j=1;
            
            try {
                while(!(dao.retrieve(i)==null)&&j<=dao.count())  /////////////////////////////////////////////////
                {
                    System.out.println(i);
           
                    try {
                        songlist[i]=dao.retrieve(i);
                    } catch (Exception ex) {
                        ex.getMessage();
                    }
                    
                    
                    
                    File f = null;
                    try {
                        f = new File(songlist[i]);
                    } catch (Exception ex) {
                        ex.getMessage();
                    }
                    
                    j++;
                    i++;
                    
                    sl.addItem(f.getName());
                    
                    
                   
                    
                    
                }  } catch (Exception ex) {
                ex.getMessage();
            }
            
            j=0;
            
            try {
                while(!(dao.retrieve(0)==null)&&j<dao.count())  /////////////////////////////////////////////////
                {
                     
                    if(dao.isFav(j)==1)      /////////////////////////////////////////
                    {
                        
                    try {
                        fsonglist[fav]=dao.retrieve(j);
                    } catch (Exception ex) {
                        ex.getMessage();
                    }
                    
                    
                    
                    File f = null;
                    try {
                        f = new File(fsonglist[fav]);
                    } catch (Exception ex) {
                        ex.getMessage();
                    }
                    
                    
                    
                    
                    sl2.addItem(f.getName());
                    
                    fav++;
                    
                    }
                    
                    j++;
                   
                    
                  
                }  } catch (Exception ex) {
                ex.getMessage();
            }
            
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {     
            MPdao dao = new MPdao();
            String url="jdbc:mysql://localhost:3306/abc";
            String username="root";
            String password="mysql!!";
            String query="update Mplayer set fav = 1 where idx ="+lastplay;
            
            fsonglist[fav++]=dao.retrieve(lastplay);
            File f = new File(dao.retrieve(lastplay));
            sl2.addItem(f.getName());
            
            
            
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(url,username,password);
            Statement st = con.createStatement();
            st.executeUpdate(query);
            
            try {
                st.close();
            } catch (SQLException ex) {
                Logger.getLogger(musicGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(musicGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(musicGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(musicGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(musicGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(musicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(musicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(musicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(musicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        
       
       
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                musicGUI dialog = new musicGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Display;
    private javax.swing.JButton Loop;
    private javax.swing.JButton Pause;
    private javax.swing.JButton Play;
    private javax.swing.JButton SelectFile;
    private javax.swing.JButton Stop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel loopcounter;
    private javax.swing.JButton next;
    private javax.swing.JButton prev;
    private javax.swing.JComboBox<String> sl;
    private javax.swing.JComboBox<String> sl2;
    // End of variables declaration//GEN-END:variables
}


